name: equilead
description: 'A new Flutter project.'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  fading_edge_scrollview: ^4.1.1
  firebase_analytics: ^10.10.5
  firebase_core: ^2.28.0
  firebase_in_app_messaging: ^0.7.5+5
  firebase_messaging: ^14.8.0
  firebase_remote_config: ^4.4.4
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^15.0.0
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  flutter_timezone: ^1.0.8
  go_router: ^13.2.0
  http: ^1.1.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  lottie: ^3.1.0
  path_provider: ^2.1.2
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  rive: ^0.13.4
  riverpod_annotation: ^2.3.3
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  signin_with_linkedin: ^1.0.0
  url_launcher: ^6.2.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9

flutter_launcher_icons:
  android: 'equilead'
  ios: false
  image_path: 'assets/app_icon/equilead_app_icon.png'
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatars/
    - assets/images/animated/
    - assets/lottie/
    - assets/rive/
    - assets/icons/
    - assets/fonts/
    - assets/app_icon/

  fonts:
    - family: General Sans
      fonts:
        - asset: assets/fonts/GeneralSans-Extralight.otf
        - asset: assets/fonts/GeneralSans-Light.otf
        - asset: assets/fonts/GeneralSans-Regular.otf
        - asset: assets/fonts/GeneralSans-Medium.otf
        - asset: assets/fonts/GeneralSans-Semibold.otf
        - asset: assets/fonts/GeneralSans-Bold.otf

    - family: Instrumental Serif
      fonts:
        - asset: assets/fonts/InstrumentSerif-Regular.ttf
        - asset: assets/fonts/InstrumentSerif-Italic.ttf
          style: italic
