class AppConstants {
  static String version = "0.0.1";
  static String orgId = '1';
  static String apiURL = 'https://equilead.hoomans.dev/';
  static int maxInviteLimit = 10;
  static int defaultStudentSubOrg = 2910;
  static String spaceManagerContact = '+919778691650';
  static int staffRoleId = 5;
  static List<double> spaceLocation = [10.0469653, 76.335211];
  static List<double> officeLocation = [9.991018, 76.314992];
  static List<String> vouchPhoneNumbers = [
    '+918281392010',
    '+919037022243',
    '+916238306211',
    '+919020024148',
    '+917025055366',
    '+917012970360'
  ];

  static String vouchWhatsappText =
      '?text=Hi%2C%0A%0AI%27m%20looking%20for%20someone%20to%20vouch%20for%20me%20for%20Equilead%20membership.%20Could%20you%20help%20me%20out%3F%20Thanks%20in%20advance%21';

  static String informTheyAreVouchedText =
      'Hey+there%21+Great+news+-+you%27ve+been+vouched+for+on+the+Equilead+app.+You+now+have+free+access+to+use+the+app+and+all+its+features.+Simply+download+Equilead+and+start+exploring.+Enjoy%21';

  static List<String> easterEggText = [
    'Hakuna Matata!',
    'Get your hands dirty!',
    'Help each other',
    'Nobody falls',
    'Never Give Up'
  ];
}

const List<String> eventIcons = [
  'assets/images/violet.svg',
  'assets/images/cyan.svg',
  'assets/images/orange.svg',
  'assets/images/paper.svg',
  'assets/images/spade.svg',
  'assets/images/earthy.svg',
  'assets/images/rings-pro.svg',
  'assets/images/rings.svg',
  'assets/images/green.svg',
  'assets/images/pink.svg',
];

const List<String> avatars = [
  'assets/images/avatars/1.png',
  'assets/images/avatars/2.png',
  'assets/images/avatars/3.png',
  'assets/images/avatars/4.png',
  'assets/images/avatars/5.png',
  'assets/images/avatars/6.png',
  'assets/images/avatars/7.png',
];

const List<String> districts = [
  'Thiruvananthapuram',
  'Kollam',
  'Pathanamthitta',
  'Alappuzha',
  'Kottayam',
  'Idukki',
  'Ernakulam',
  'Thrissur',
  'Palakkad',
  'Malappuram',
  'Kozhikode',
  'Wayanad',
  'Kannur',
  'Kasaragod',
];

const Map<String, String> courses = {
  "ba": "Bachelor of Arts (BA)",
  "btech": "Bachelor of Technology (B.Tech)",
  "mtech": "Master of Technology (M.Tech)",
  "bcom": "Bachelor of Commerce (B.Com)",
  "mcom": "Master of Commerce (M.Com)",
  "bsc": "Bachelor of Science (BSc)",
  "msc": "Master of Science (MSc)",
  "phd": "Doctor of Philosophy (PhD)",
  "diploma": "Diploma",
  "advanced diploma": "Advanced Diploma",
  "bba": "Bachelor of Business Administration (BBA)",
  "mba": "Master of Business Administration (MBA)",
  "bed": "Bachelor of Education (B.Ed)",
  "med": "Master of Education (M.Ed)",
  "llb": "Bachelor of Laws (LLB)",
  "llm": "Master of Laws (LLM)",
  "bca": "Bachelor of Computer Applications (BCA)",
  "mca": "Master of Computer Applications (MCA)",
  "bfa": "Bachelor of Fine Arts (BFA)",
  "mfa": "Master of Fine Arts (MFA)",
  "bpharm": "Bachelor of Pharmacy (B.Pharm)",
  "mpharm": "Master of Pharmacy (M.Pharm)",
  "bds": "Bachelor of Dental Surgery (BDS)",
  "mds": "Master of Dental Surgery (MDS)",
  "mbbs": "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
  "md": "Doctor of Medicine (MD)",
  "ms": "Master of Surgery (MS)",
  "barch": "Bachelor of Architecture (B.Arch)",
  "march": "Master of Architecture (M.Arch)",
  "bpt": "Bachelor of Physiotherapy (BPT)",
  "mpt": "Master of Physiotherapy (MPT)",
  "bsw": "Bachelor of Social Work (BSW)",
  "msw": "Master of Social Work (MSW)",
  "bhm": "Bachelor of Hotel Management (BHM)",
  "mhm": "Master of Hotel Management (MHM)",
  "blisc": "Bachelor of Library Science (BLISc)",
  "mlisc": "Master of Library Science (MLISc)",
  "bped": "Bachelor of Physical Education (B.P.Ed)",
  "mped": "Master of Physical Education (M.P.Ed)",
  "bvsc": "Bachelor of Veterinary Science (BVSc)",
  "mvsc": "Master of Veterinary Science (MVSc)",
  "other": "Others"
};

const List<Map<String, String>> streams = [
  {"course": "acca", "type": "other"},
  {"course": "adfa", "type": "other"},
  {"course": "adia", "type": "other"},
  {
    "course": "advanced diploma dairy science & technology",
    "type": "advanced diploma"
  },
  {"course": "aei", "type": "other"},
  {"course": "afzal-ul-ulama", "type": "other"},
  {"course": "agr", "type": "other"},
  {"course": "ane", "type": "other"},
  {"course": "aut", "type": "other"},
  {"course": "b voc", "type": "other"},
  {"course": "animation", "type": "ba"},
  {"course": "arabic", "type": "ba"},
  {"course": "bharatanatyam", "type": "ba"},
  {"course": "chenda", "type": "ba"},
  {"course": "communicative english", "type": "ba"},
  {"course": "computer application", "type": "ba"},
  {"course": "dance", "type": "ba"},
  {"course": "development economics", "type": "ba"},
  {"course": "economics", "type": "ba"},
  {"course": "english", "type": "ba"},
  {"course": "foreign trade", "type": "ba"},
  {"course": "french", "type": "ba"},
  {"course": "functional", "type": "ba"},
  {"course": "functional arabic", "type": "ba"},
  {"course": "functional english", "type": "ba"},
  {"course": "hindi", "type": "ba"},
  {"course": "history", "type": "ba"},
  {"course": "indian culture", "type": "ba"},
  {"course": "international relations", "type": "ba"},
  {"course": "islamic history", "type": "ba"},
  {"course": "islamic studies", "type": "ba"},
  {"course": "kannada", "type": "ba"},
  {"course": "kathakali", "type": "ba"},
  {"course": "llb", "type": "ba"},
  {"course": "maddalam", "type": "ba"},
  {"course": "malayalam", "type": "ba"},
  {"course": "mass communication", "type": "ba"},
  {"course": "mohiniyattam", "type": "ba"},
  {"course": "multimedia", "type": "ba"},
  {"course": "music", "type": "ba"},
  {"course": "nyaya", "type": "ba"},
  {"course": "philosophy", "type": "ba"},
  {"course": "political science", "type": "ba"},
  {"course": "politics", "type": "ba"},
  {"course": "psychology", "type": "ba"},
  {"course": "sahitya", "type": "ba"},
  {"course": "sanskrit", "type": "ba"},
  {"course": "sociology", "type": "ba"},
  {"course": "tamil", "type": "ba"},
  {"course": "tourism & travel", "type": "ba"},
  {"course": "transilation", "type": "ba"},
  {"course": "travel & tourism", "type": "ba"},
  {"course": "vedanda", "type": "ba"},
  {"course": "visual communication", "type": "ba"},
  {"course": "vyakarana", "type": "ba"},
  {"course": "west asian studies", "type": "ba"},
  {"course": "bae", "type": "other"},
  {"course": "bag", "type": "other"},
  {"course": "bam", "type": "other"},
  {"course": "bams", "type": "other"},
  {"course": "barch", "type": "other"},
  {"course": "barch interior design", "type": "other"},
  {"course": "barch planning", "type": "other"},
  {"course": "baslp", "type": "other"},
  {"course": "bb", "type": "other"},
  {"course": "bba", "type": "other"},
  {"course": "bba finance", "type": "other"},
  {"course": "bba maritime logistics", "type": "other"},
  {"course": "bba travel & tourism management", "type": "other"},
  {"course": "bbm", "type": "other"},
  {"course": "bbm finance", "type": "other"},
  {"course": "bca", "type": "other"},
  {"course": "bca mathematics & statistics", "type": "other"},
  {"course": "bce", "type": "other"},
  {"course": "bche", "type": "other"},
  {"course": "bcl", "type": "other"},
  {"course": "aii finance", "type": "bcom"},
  {"course": "banking & insurance", "type": "bcom"},
  {"course": "computer application", "type": "bcom"},
  {"course": "co-operation", "type": "bcom"},
  {"course": "finance", "type": "bcom"},
  {"course": "hotel management & catering technology", "type": "bcom"},
  {"course": "hotel management catering technology", "type": "bcom"},
  {"course": "income tax", "type": "bcom"},
  {"course": "islamic finance", "type": "bcom"},
  {"course": "llb", "type": "bcom"},
  {"course": "marketing", "type": "bcom"},
  {"course": "tax procedure", "type": "bcom"},
  {"course": "taxation", "type": "bcom"},
  {"course": "tourism", "type": "bcom"},
  {"course": "travel & tourism", "type": "bcom"},
  {"course": "bcs", "type": "other"},
  {"course": "bcvt", "type": "other"},
  {"course": "bd", "type": "other"},
  {"course": "bds", "type": "other"},
  {"course": "be", "type": "other"},
  {"course": "be", "type": "other"},
  {"course": "be aeronautical engineering", "type": "other"},
  {"course": "be agricultural engineering", "type": "other"},
  {"course": "be apparel technology", "type": "other"},
  {"course": "be applied electronics engineering", "type": "other"},
  {"course": "be automobile engineering", "type": "other"},
  {"course": "be bioinformatics", "type": "other"},
  {"course": "be biomedical engineering", "type": "other"},
  {"course": "be biotechnology engineering", "type": "other"},
  {"course": "be chemical engineering", "type": "other"},
  {"course": "be civil engineering", "type": "other"},
  {"course": "be computer science & engineering", "type": "other"},
  {"course": "be computer science & software engineering", "type": "other"},
  {"course": "be electrical & electronics engineering", "type": "other"},
  {"course": "be electrical engineering", "type": "other"},
  {"course": "be electronics & communication engineering", "type": "other"},
  {"course": "be electronics & instrumentation", "type": "other"},
  {"course": "be geoinformatics", "type": "other"},
  {"course": "be humanities &", "type": "other"},
  {"course": "be information technology", "type": "other"},
  {"course": "be instrumentation & control system", "type": "other"},
  {"course": "be marine engineering", "type": "other"},
  {"course": "be mechanical engineering", "type": "other"},
  {"course": "be mechatronics engineering", "type": "other"},
  {"course": "be medical electronics engineering", "type": "other"},
  {"course": "be metallurgical engineering", "type": "other"},
  {"course": "be petroleum engineering", "type": "other"},
  {"course": "be production engineering", "type": "other"},
  {"course": "be robotics & automation engineering", "type": "other"},
  {"course": "be sandwich engineering", "type": "other"},
  {"course": "bed", "type": "other"},
  {"course": "bed arabic", "type": "other"},
  {"course": "bed commerce", "type": "other"},
  {"course": "bed computer science", "type": "other"},
  {"course": "bed english", "type": "other"},
  {"course": "bed geography", "type": "other"},
  {"course": "bed hearing impaired", "type": "other"},
  {"course": "bed hindi", "type": "other"},
  {"course": "bed information technology", "type": "other"},
  {"course": "bed malayalam", "type": "other"},
  {"course": "bed mathematics", "type": "other"},
  {"course": "bed natural science", "type": "other"},
  {"course": "bed physical science", "type": "other"},
  {"course": "bed sanskrit", "type": "other"},
  {"course": "bed social science", "type": "other"},
  {"course": "bed social studies", "type": "other"},
  {"course": "bed special education", "type": "other"},
  {"course": "bed tamil", "type": "other"},
  {"course": "bee", "type": "other"},
  {"course": "bems", "type": "other"},
  {"course": "bf", "type": "other"},
  {"course": "bfa", "type": "other"},
  {"course": "bfa", "type": "other"},
  {"course": "bfa applied art", "type": "other"},
  {"course": "bfa for hearing impaired", "type": "other"},
  {"course": "bfa painting", "type": "other"},
  {"course": "bfa sculpture", "type": "other"},
  {"course": "bfa visual arts", "type": "other"},
  {"course": "bfs", "type": "other"},
  {"course": "bfs nautical science", "type": "other"},
  {"course": "bft", "type": "other"},
  {"course": "bft ba film and television", "type": "other"},
  {"course": "bha", "type": "other"},
  {"course": "bhm", "type": "other"},
  {
    "course": "bhm bachelor of hotel management & catering technology",
    "type": "other"
  },
  {"course": "bhm catering science & hotel management", "type": "other"},
  {"course": "bhmct", "type": "other"},
  {"course": "bhms", "type": "other"},
  {"course": "bio", "type": "other"},
  {"course": "biochemistry", "type": "other"},
  {"course": "bj", "type": "other"},
  {"course": "bli", "type": "other"},
  {"course": "blisc", "type": "other"},
  {"course": "blit", "type": "other"},
  {"course": "blitt", "type": "other"},
  {"course": "bls", "type": "other"},
  {"course": "bm", "type": "other"},
  {"course": "bme", "type": "other"},
  {"course": "bmlt", "type": "other"},
  {"course": "bmmc", "type": "other"},
  {"course": "bms", "type": "other"},
  {"course": "bms", "type": "other"},
  {"course": "bn", "type": "other"},
  {"course": "bopt", "type": "other"},
  {"course": "bot", "type": "other"},
  {"course": "bot occupational therapy", "type": "other"},
  {"course": "bpa", "type": "other"},
  {"course": "bpa vocal", "type": "other"},
  {"course": "bpe", "type": "other"},
  {"course": "bped", "type": "other"},
  {"course": "bpharm", "type": "other"},
  {"course": "bpharm ayurveda", "type": "other"},
  {"course": "bpt", "type": "other"},
  {"course": "bre", "type": "other"},
  {"course": "brit", "type": "other"},
  {"course": "bs", "type": "other"},
  {"course": "applied physics", "type": "bsc"},
  {"course": "aquaculture", "type": "bsc"},
  {"course": "audiology & speech pathology", "type": "bsc"},
  {"course": "ayurveda nursing", "type": "bsc"},
  {"course": "biochemistry", "type": "bsc"},
  {"course": "bioinformatics", "type": "bsc"},
  {"course": "biological techniques & specimen preparation", "type": "bsc"},
  {"course": "biology & biotechnology", "type": "bsc"},
  {"course": "biotechnology", "type": "bsc"},
  {"course": "botany", "type": "bsc"},
  {"course": "botany & biotechnology", "type": "bsc"},
  {"course": "botany with chemistry", "type": "bsc"},
  {"course": "catering and hotel administration", "type": "bsc"},
  {"course": "catering science & hotel management", "type": "bsc"},
  {"course": "chemistry", "type": "bsc"},
  {"course": "chemistry & industrial chemistry", "type": "bsc"},
  {"course": "clinical nutrition & dietetics", "type": "bsc"},
  {"course": "computer science", "type": "bsc"},
  {"course": "computer science for hearing impaired", "type": "bsc"},
  {"course": "computer technology", "type": "bsc"},
  {"course": "costume & fashion designing", "type": "bsc"},
  {"course": "electronic equipment maintanence", "type": "bsc"},
  {"course": "electronics", "type": "bsc"},
  {"course": "electronics & communication", "type": "bsc"},
  {"course": "environment & water management", "type": "bsc"},
  {"course": "environmental science", "type": "bsc"},
  {"course": "family & community science", "type": "bsc"},
  {"course": "food & nutrition", "type": "bsc"},
  {"course": "food science & quality control", "type": "bsc"},
  {"course": "food technology", "type": "bsc"},
  {"course": "forestry", "type": "bsc"},
  {"course": "geography", "type": "bsc"},
  {"course": "geology", "type": "bsc"},
  {"course": "home science", "type": "bsc"},
  {"course": "hotel management & catering science", "type": "bsc"},
  {"course": "hotel management & culinary arts", "type": "bsc"},
  {"course": "industrial chemistry with mathematics & physics", "type": "bsc"},
  {"course": "industrial electronics", "type": "bsc"},
  {"course": "industrial fish & fisheries", "type": "bsc"},
  {"course": "industrial microbiology", "type": "bsc"},
  {"course": "information system & management", "type": "bsc"},
  {"course": "information technology", "type": "bsc"},
  {"course": "mathematics", "type": "bsc"},
  {"course": "medical laboratory technology", "type": "bsc"},
  {"course": "microbiology", "type": "bsc"},
  {"course": "mlt", "type": "bsc"},
  {"course": "nuclear medicine", "type": "bsc"},
  {"course": "nursing", "type": "bsc"},
  {"course": "nutrition & dietritics", "type": "bsc"},
  {"course": "opto electronics", "type": "bsc"},
  {"course": "optometry", "type": "bsc"},
  {"course": "perfusion technology", "type": "bsc"},
  {"course": "petrochemicals", "type": "bsc"},
  {"course": "physics", "type": "bsc"},
  {"course": "physics instrumentation", "type": "bsc"},
  {"course": "physiotherapy", "type": "bsc"},
  {"course": "polymer chemistry", "type": "bsc"},
  {"course": "psychology", "type": "bsc"},
  {"course": "radiotherapy technology", "type": "bsc"},
  {"course": "ship building & repair", "type": "bsc"},
  {"course": "software engineering", "type": "bsc"},
  {"course": "speech & hearing", "type": "bsc"},
  {"course": "statistics", "type": "bsc"},
  {"course": "visual communication", "type": "bsc"},
  {"course": "zoology", "type": "bsc"},
  {"course": "bsed", "type": "other"},
  {"course": "bsms", "type": "other"},
  {"course": "bsw", "type": "other"},
  {"course": "bt", "type": "other"},
  {"course": "aeronautical engineering", "type": "btech"},
  {"course": "aerospace engineering", "type": "btech"},
  {"course": "agricultural engineering", "type": "btech"},
  {"course": "applied electronics & instrumentation", "type": "btech"},
  {"course": "automobile engineering", "type": "btech"},
  {"course": "avionics", "type": "btech"},
  {"course": "bio-mechanical engineering", "type": "btech"},
  {"course": "biomedical engineering", "type": "btech"},
  {"course": "biotechnology & biochemical engineering", "type": "btech"},
  {"course": "biotechnology engineering", "type": "btech"},
  {"course": "ceramic technology", "type": "btech"},
  {"course": "chemical engineering", "type": "btech"},
  {"course": "civil engineering", "type": "btech"},
  {"course": "computer science", "type": "btech"},
  {"course": "dairy science & technology", "type": "btech"},
  {"course": "electrical & electronics", "type": "btech"},
  {"course": "electro chemical engineering", "type": "btech"},
  {"course": "electronics & biomedical engineering", "type": "btech"},
  {"course": "electronics & communication", "type": "btech"},
  {"course": "electronics & communication engineering", "type": "btech"},
  {"course": "electronics & electronics engineering", "type": "btech"},
  {"course": "electronics & instrumentation", "type": "btech"},
  {"course": "environmental engineering", "type": "btech"},
  {"course": "fashion technology", "type": "btech"},
  {"course": "food technology", "type": "btech"},
  {"course": "industrial biotechnology", "type": "btech"},
  {"course": "information technology", "type": "btech"},
  {"course": "instrumentation", "type": "btech"},
  {"course": "instrumentation & control", "type": "btech"},
  {"course": "instrumentation engineering", "type": "btech"},
  {"course": "leather technology", "type": "btech"},
  {"course": "mechanical engineering", "type": "btech"},
  {"course": "petroleum refining & petro chemical technology", "type": "btech"},
  {"course": "pharmaceutical technology", "type": "btech"},
  {"course": "plastic technology", "type": "btech"},
  {"course": "polymer engineering", "type": "btech"},
  {"course": "production engineering", "type": "btech"},
  {"course": "textile technology", "type": "btech"},
  {"course": "bthm", "type": "other"},
  {"course": "bthm", "type": "other"},
  {"course": "btm", "type": "other"},
  {"course": "bts", "type": "other"},
  {"course": "bts tourism", "type": "other"},
  {"course": "btth", "type": "other"},
  {"course": "bttm", "type": "other"},
  {"course": "bums", "type": "other"},
  {"course": "bvsc", "type": "other"},
  {"course": "ca", "type": "other"},
  {"course": "cab", "type": "other"},
  {"course": "cacfa", "type": "other"},
  {"course": "cat", "type": "other"},
  {"course": "cba", "type": "other"},
  {"course": "ce", "type": "other"},
  {"course": "cee", "type": "other"},
  {"course": "cep", "type": "other"},
  {"course": "cepa", "type": "other"},
  {"course": "cer", "type": "other"},
  {"course": "cfa", "type": "other"},
  {"course": "che", "type": "other"},
  {"course": "cia", "type": "other"},
  {"course": "cima", "type": "other"},
  {"course": "civ", "type": "other"},
  {"course": "cma", "type": "other"},
  {"course": "computer science", "type": "other"},
  {"course": "cpa", "type": "other"},
  {"course": "cpe", "type": "other"},
  {"course": "cs", "type": "other"},
  {"course": "cse", "type": "other"},
  {"course": "cseet", "type": "other"},
  {"course": "css", "type": "other"},
  {"course": "cwa", "type": "other"},
  {"course": "d ortho", "type": "other"},
  {"course": "da", "type": "other"},
  {"course": "da", "type": "other"},
  {"course": "da", "type": "other"},
  {"course": "dairy diploma programme", "type": "diploma"},
  {"course": "dam", "type": "other"},
  {"course": "dam", "type": "other"},
  {"course": "das", "type": "other"},
  {"course": "dba", "type": "other"},
  {"course": "dbat", "type": "other"},
  {"course": "dc", "type": "other"},
  {"course": "dcd", "type": "other"},
  {"course": "dcfa", "type": "other"},
  {"course": "dch", "type": "other"},
  {"course": "dch", "type": "other"},
  {"course": "dcm", "type": "other"},
  {"course": "dcp", "type": "other"},
  {"course": "dcpa", "type": "other"},
  {"course": "dcpm", "type": "other"},
  {"course": "dd", "type": "other"},
  {"course": "dd", "type": "other"},
  {"course": "dd&std", "type": "other"},
  {"course": "ddk", "type": "other"},
  {"course": "ddm", "type": "other"},
  {"course": "dds", "type": "other"},
  {"course": "ddvd", "type": "other"},
  {"course": "ddvl", "type": "other"},
  {"course": "de", "type": "other"},
  {"course": "ded", "type": "other"},
  {"course": "dffl", "type": "other"},
  {"course": "dfm", "type": "other"},
  {"course": "dfp", "type": "other"},
  {"course": "dgo", "type": "other"},
  {"course": "dgo’", "type": "other"},
  {"course": "dha", "type": "other"},
  {"course": "dhe", "type": "other"},
  {"course": "diploma agriculture technology", "type": "diploma"},
  {"course": "diploma anaesthesiology", "type": "diploma"},
  {"course": "diploma apparel technology", "type": "diploma"},
  {"course": "diploma archite", "type": "diploma"},
  {"course": "diploma architectural assistantship", "type": "diploma"},
  {"course": "diploma automobile technology", "type": "diploma"},
  {"course": "diploma brackishwater & marine aquaculture", "type": "diploma"},
  {"course": "diploma catering and hotel administration", "type": "diploma"},
  {"course": "diploma ceramic technology", "type": "diploma"},
  {"course": "diploma chemical engineering", "type": "diploma"},
  {"course": "diploma civil engineering", "type": "diploma"},
  {"course": "diploma clinical pathology", "type": "diploma"},
  {"course": "diploma computer eng", "type": "diploma"},
  {"course": "diploma computer engineering", "type": "diploma"},
  {"course": "diploma computer networking", "type": "diploma"},
  {"course": "diploma computer technology", "type": "diploma"},
  {"course": "diploma direction", "type": "diploma"},
  {"course": "diploma electrical & electronics engineering", "type": "diploma"},
  {
    "course": "diploma electronics & communication engineering",
    "type": "diploma"
  },
  {"course": "diploma environmental pollution & control", "type": "diploma"},
  {"course": "diploma fashion technology", "type": "diploma"},
  {"course": "diploma film tech & t v production", "type": "diploma"},
  {"course": "diploma fisheri", "type": "diploma"},
  {"course": "diploma garment technology", "type": "diploma"},
  {"course": "diploma hearing language & speech", "type": "diploma"},
  {"course": "diploma information technology", "type": "diploma"},
  {"course": "diploma instrumentation & control engineer", "type": "diploma"},
  {
    "course": "diploma instrumentation & control engineering",
    "type": "diploma"
  },
  {"course": "diploma laboratory techniques", "type": "diploma"},
  {"course": "diploma leather technology", "type": "diploma"},
  {"course": "diploma marine engineering", "type": "diploma"},
  {"course": "diploma mechanical engineering", "type": "diploma"},
  {"course": "diploma mechatronics engineering", "type": "diploma"},
  {"course": "diploma modern office", "type": "diploma"},
  {"course": "diploma nursing", "type": "diploma"},
  {"course": "diploma ophthalmology", "type": "diploma"},
  {"course": "diploma oto rhino laryngology", "type": "diploma"},
  {"course": "diploma paper technology", "type": "diploma"},
  {"course": "diploma petrochemical engineering", "type": "diploma"},
  {"course": "diploma plastic engineering", "type": "diploma"},
  {"course": "diploma polymer technology", "type": "diploma"},
  {"course": "diploma poultry production", "type": "diploma"},
  {"course": "diploma printing technology", "type": "diploma"},
  {"course": "diploma production engineering", "type": "diploma"},
  {"course": "diploma professional cookery", "type": "diploma"},
  {"course": "diploma prosthetics & orthotics", "type": "diploma"},
  {"course": "diploma screen play writing & tv production", "type": "diploma"},
  {"course": "diploma sugar technology", "type": "diploma"},
  {"course": "diploma textile processing", "type": "diploma"},
  {"course": "diploma textile technology", "type": "diploma"},
  {"course": "dj", "type": "other"},
  {"course": "djs", "type": "other"},
  {"course": "dlh", "type": "other"},
  {"course": "dll", "type": "other"},
  {"course": "dlo", "type": "other"},
  {"course": "dlo", "type": "other"},
  {"course": "dlo", "type": "other"},
  {"course": "dls", "type": "other"},
  {"course": "dlsc", "type": "other"},
  {"course": "dm", "type": "other"},
  {"course": "dm", "type": "other"},
  {"course": "dm cardiac anesthes", "type": "other"},
  {"course": "dm cardiology", "type": "other"},
  {"course": "dm endocrinology", "type": "other"},
  {"course": "dm gastroenterology", "type": "other"},
  {"course": "dm medical oncology", "type": "other"},
  {"course": "dm nephrology", "type": "other"},
  {"course": "dm neuroanaesthesia", "type": "other"},
  {
    "course": "dm neuroimaging & interventional neuroradiology",
    "type": "other"
  },
  {"course": "dm neurology", "type": "other"},
  {"course": "dm pediatric cardiology", "type": "other"},
  {"course": "dm pulmonary medicine", "type": "other"},
  {"course": "dm&ch", "type": "other"},
  {"course": "dmch", "type": "other"},
  {"course": "dmd", "type": "other"},
  {"course": "dmlt", "type": "other"},
  {"course": "dmp", "type": "other"},
  {"course": "dmpb", "type": "other"},
  {"course": "dmr", "type": "other"},
  {"course": "dmrd", "type": "other"},
  {"course": "dmrd", "type": "other"},
  {"course": "dmre", "type": "other"},
  {"course": "dmrit", "type": "other"},
  {"course": "dmrt", "type": "other"},
  {"course": "dms", "type": "other"},
  {"course": "dmt", "type": "other"},
  {"course": "dnt", "type": "other"},
  {"course": "do", "type": "other"},
  {"course": "do", "type": "other"},
  {"course": "doa", "type": "other"},
  {"course": "doe", "type": "other"},
  {"course": "doms", "type": "other"},
  {"course": "dortho", "type": "other"},
  {"course": "dortho", "type": "other"},
  {"course": "dotat", "type": "other"},
  {"course": "dpa", "type": "other"},
  {"course": "dpca", "type": "other"},
  {"course": "dpe", "type": "other"},
  {"course": "dped", "type": "other"},
  {"course": "dph", "type": "other"},
  {"course": "dph", "type": "other"},
  {"course": "dpharm", "type": "other"},
  {"course": "dpm", "type": "other"},
  {"course": "dpm&r", "type": "other"},
  {"course": "dre", "type": "other"},
  {"course": "drt", "type": "other"},
  {"course": "dsc", "type": "other"},
  {"course": "dss", "type": "other"},
  {"course": "dstd", "type": "other"},
  {"course": "dsw", "type": "other"},
  {"course": "dtcd", "type": "other"},
  {"course": "dtd", "type": "other"},
  {"course": "dtd", "type": "other"},
  {"course": "dtm&h", "type": "other"},
  {"course": "dtrd", "type": "other"},
  {"course": "dv", "type": "other"},
  {"course": "dv&d", "type": "other"},
  {"course": "dvm", "type": "other"},
  {"course": "ece", "type": "other"},
  {"course": "ecm", "type": "other"},
  {"course": "ecs", "type": "other"},
  {"course": "edd", "type": "other"},
  {"course": "ee", "type": "other"},
  {"course": "eee", "type": "other"},
  {"course": "eie", "type": "other"},
  {"course": "em", "type": "other"},
  {"course": "emet", "type": "other"},
  {"course": "etm", "type": "other"},
  {"course": "fds", "type": "other"},
  {"course": "fpt", "type": "other"},
  {"course": "fsp", "type": "other"},
  {"course": "gin", "type": "other"},
  {"course": "gnm", "type": "other"},
  {"course": "gnm", "type": "other"},
  {"course": "gnm diploma", "type": "diploma"},
  {"course": "health inspector course", "type": "other"},
  {"course": "ice", "type": "other"},
  {"course": "ie", "type": "other"},
  {"course": "inf", "type": "other"},
  {"course": "instrumental courses dance", "type": "other"},
  {"course": "instrumental courses mridangam", "type": "other"},
  {"course": "instrumental courses veena", "type": "other"},
  {"course": "instrumental courses violin", "type": "other"},
  {"course": "ipe", "type": "other"},
  {"course": "ist", "type": "other"},
  {"course": "llb", "type": "other"},
  {"course": "llm", "type": "other"},
  {"course": "llm administrative law", "type": "other"},
  {"course": "llm commercial law", "type": "other"},
  {"course": "llm constitutional law", "type": "other"},
  {"course": "llm international law", "type": "other"},
  {"course": "ma", "type": "other"},
  {"course": "ma animation", "type": "other"},
  {"course": "ma arabic", "type": "other"},
  {"course": "ma cinema & television", "type": "other"},
  {"course": "ma economics", "type": "other"},
  {"course": "ma english", "type": "other"},
  {"course": "ma graphic design", "type": "other"},
  {"course": "ma hindi", "type": "other"},
  {"course": "ma histor", "type": "other"},
  {"course": "ma history", "type": "other"},
  {"course": "ma human resource management", "type": "other"},
  {"course": "ma international relations & politics", "type": "other"},
  {"course": "ma islamic finance", "type": "other"},
  {"course": "ma islamic studies", "type": "other"},
  {"course": "ma linguistics & language technology", "type": "other"},
  {"course": "ma malayalam", "type": "other"},
  {"course": "ma multimedia", "type": "other"},
  {"course": "ma nyaya", "type": "other"},
  {"course": "ma political science", "type": "other"},
  {"course": "ma politics", "type": "other"},
  {"course": "ma post afzal ul-ulama", "type": "other"},
  {"course": "ma sanskrit general", "type": "other"},
  {"course": "ma sanskrit nyaya", "type": "other"},
  {"course": "ma sanskrit sahitya", "type": "other"},
  {"course": "ma sanskrit vedanta", "type": "other"},
  {"course": "ma sanskrit vyakarana", "type": "other"},
  {"course": "ma sociology", "type": "other"},
  {"course": "ma tamil", "type": "other"},
  {"course": "ma urdu", "type": "other"},
  {"course": "ma visual communication", "type": "other"},
  {"course": "ma vyakarana", "type": "other"},
  {"course": "maeroe", "type": "other"},
  {"course": "march", "type": "other"},
  {"course": "march digital", "type": "other"},
  {"course": "march landscape", "type": "other"},
  {"course": "march planning", "type": "other"},
  {"course": "march real estate development", "type": "other"},
  {"course": "marine electrician", "type": "other"},
  {"course": "marine fitter", "type": "other"},
  {"course": "marine pipe fitter", "type": "other"},
  {"course": "marine welder", "type": "other"},
  {"course": "maslp", "type": "other"},
  {"course": "mat", "type": "other"},
  {"course": "mba", "type": "other"},
  {"course": "mba agri-business management", "type": "other"},
  {"course": "mbbs", "type": "other"},
  {"course": "mbl", "type": "other"},
  {"course": "mca", "type": "other"},
  {"course": "mce", "type": "other"},
  {"course": "mch", "type": "other"},
  {"course": "mch", "type": "other"},
  {"course": "mch cardiovascular & thoracic surgery", "type": "other"},
  {"course": "mch neuro surgery", "type": "other"},
  {"course": "mch plastic surgery", "type": "other"},
  {"course": "mch surgical oncology", "type": "other"},
  {"course": "mch vascular surgery", "type": "other"},
  {"course": "mci", "type": "other"},
  {"course": "mcj", "type": "other"},
  {"course": "banking", "type": "mcom"},
  {"course": "computer application", "type": "mcom"},
  {"course": "e-commerce", "type": "mcom"},
  {"course": "finance", "type": "mcom"},
  {"course": "finance stream", "type": "mcom"},
  {"course": "financial management", "type": "mcom"},
  {"course": "marketing", "type": "mcom"},
  {"course": "taxation", "type": "mcom"},
  {"course": "mcs", "type": "other"},
  {"course": "mct", "type": "other"},
  {"course": "md", "type": "other"},
  {"course": "md agada tantra", "type": "other"},
  {"course": "md anaesthesia", "type": "other"},
  {"course": "md anaesthesiology", "type": "other"},
  {"course": "md anatomy", "type": "other"},
  {"course": "md ayurveda", "type": "other"},
  {"course": "md ayurveda siddhant", "type": "other"},
  {"course": "md bhaisajya kalpana", "type": "other"},
  {"course": "md biochemistry", "type": "other"},
  {"course": "md community medicine", "type": "other"},
  {"course": "md dermatology", "type": "other"},
  {"course": "md dravyaguna", "type": "other"},
  {"course": "md dvl", "type": "other"},
  {"course": "md forensic medicine", "type": "other"},
  {"course": "md general medicine", "type": "other"},
  {"course": "md general surgery", "type": "other"},
  {"course": "md gunapadam", "type": "other"},
  {"course": "md homeopathic philosophy", "type": "other"},
  {"course": "md homoeo materia medica", "type": "other"},
  {"course": "md homoeo repertory", "type": "other"},
  {"course": "md homoeopathic pharmacy", "type": "other"},
  {"course": "md homoeopathic philosophy", "type": "other"},
  {"course": "md kaumar bhritya", "type": "other"},
  {"course": "md kayachikiltsa", "type": "other"},
  {"course": "md kayachikitsa", "type": "other"},
  {"course": "md kriyasareera", "type": "other"},
  {"course": "md kuzanthai maruthuvam", "type": "other"},
  {"course": "md manasika roga", "type": "other"},
  {"course": "md maruthuvam", "type": "other"},
  {"course": "md materia medica", "type": "other"},
  {"course": "md medicine", "type": "other"},
  {"course": "md microbiology", "type": "other"},
  {"course": "md nanju noolum maruthuva neethi noolum", "type": "other"},
  {"course": "md noi nadal", "type": "other"},
  {"course": "md obstetrics & gynaecology", "type": "other"},
  {
    "course": "md organon of medicine & homoeopathic philosophy",
    "type": "other"
  },
  {"course": "md paediatrics", "type": "other"},
  {"course": "md panchakarma", "type": "other"},
  {"course": "md pathology", "type": "other"},
  {"course": "md pediatrics", "type": "other"},
  {"course": "md pharmacology", "type": "other"},
  {"course": "md physiology", "type": "other"},
  {"course": "md prasuti tantra", "type": "other"},
  {"course": "md psychiatry", "type": "other"},
  {"course": "md pulmonary medicine", "type": "other"},
  {"course": "md radiodiagnosis", "type": "other"},
  {"course": "md radiology", "type": "other"},
  {"course": "md radiotherapy", "type": "other"},
  {"course": "md rasasastra", "type": "other"},
  {"course": "md repertory", "type": "other"},
  {"course": "md roganidana", "type": "other"},
  {"course": "md salyatantra", "type": "other"},
  {"course": "md shalakya", "type": "other"},
  {"course": "md sirappu maruthuvam", "type": "other"},
  {"course": "md skin & vd", "type": "other"},
  {"course": "md surgery", "type": "other"},
  {"course": "md swasthavritta", "type": "other"},
  {"course": "md tuberculosis & respiratory diseases", "type": "other"},
  {"course": "mdiv", "type": "other"},
  {"course": "mds", "type": "other"},
  {"course": "mds community dentistry", "type": "other"},
  {"course": "mds conservative dentistry", "type": "other"},
  {"course": "mds oral & maxillofacial surgery", "type": "other"},
  {"course": "mds oral medicine", "type": "other"},
  {"course": "mds oral pathology", "type": "other"},
  {"course": "mds orthodintics & dentofacial orthopaedics", "type": "other"},
  {"course": "mds orthodontics", "type": "other"},
  {"course": "mds pedodontics & preventive dentistry", "type": "other"},
  {"course": "mds periodontics", "type": "other"},
  {"course": "mds prosthetics", "type": "other"},
  {"course": "mds prosthodontics", "type": "other"},
  {"course": "me", "type": "other"},
  {"course": "me", "type": "other"},
  {"course": "me aeronautical engineering", "type": "other"},
  {"course": "me applied electronics", "type": "other"},
  {"course": "me biometrics & cyber security", "type": "other"},
  {"course": "me cad", "type": "other"},
  {"course": "me cad/cam", "type": "other"},
  {"course": "me communication", "type": "other"},
  {"course": "me communication & networking", "type": "other"},
  {"course": "me communication engineering", "type": "other"},
  {"course": "me communication systems", "type": "other"},
  {"course": "me computer & communication engineering", "type": "other"},
  {"course": "me computer aided designs", "type": "other"},
  {"course": "me computer integrated manufacturing", "type": "other"},
  {"course": "me computer science & engineering", "type": "other"},
  {"course": "me construction engineering & management", "type": "other"},
  {"course": "me electronics & communication", "type": "other"},
  {"course": "me embedded systems", "type": "other"},
  {"course": "me engineering design", "type": "other"},
  {"course": "me environmental engineering", "type": "other"},
  {"course": "me industrial safety & engineering", "type": "other"},
  {"course": "me management", "type": "other"},
  {"course": "me manufacturing", "type": "other"},
  {"course": "me network engineering", "type": "other"},
  {"course": "me optical communication", "type": "other"},
  {"course": "me power electronics", "type": "other"},
  {"course": "me power electronics & drives", "type": "other"},
  {"course": "me power systems engineering", "type": "other"},
  {"course": "me structural engineering", "type": "other"},
  {"course": "me thermal engineering", "type": "other"},
  {"course": "me vlsi & embedded systems", "type": "other"},
  {"course": "mec", "type": "other"},
  {"course": "med", "type": "other"},
  {"course": "med commerce", "type": "other"},
  {"course": "med education", "type": "other"},
  {"course": "med english", "type": "other"},
  {"course": "med hindi", "type": "other"},
  {"course": "med malayalam", "type": "other"},
  {"course": "med mathematics", "type": "other"},
  {"course": "med natural science", "type": "other"},
  {"course": "med physics", "type": "other"},
  {"course": "med science", "type": "other"},
  {"course": "med social science", "type": "other"},
  {"course": "med special education", "type": "other"},
  {"course": "meng", "type": "other"},
  {"course": "met", "type": "other"},
  {"course": "mfa", "type": "other"},
  {"course": "mfa", "type": "other"},
  {"course": "mfa creative sculpture", "type": "other"},
  {"course": "mfa mural", "type": "other"},
  {"course": "mfa portraiture", "type": "other"},
  {"course": "mha", "type": "other"},
  {"course": "mhrm", "type": "other"},
  {"course": "microbiology", "type": "other"},
  {"course": "min", "type": "other"},
  {"course": "mjc", "type": "other"},
  {"course": "mla", "type": "other"},
  {"course": "mlisc", "type": "other"},
  {"course": "mlitt", "type": "other"},
  {"course": "mll", "type": "other"},
  {"course": "mls", "type": "other"},
  {"course": "mlt", "type": "other"},
  {"course": "mm", "type": "other"},
  {"course": "mmb", "type": "other"},
  {"course": "mme", "type": "other"},
  {"course": "mme", "type": "other"},
  {"course": "mmh", "type": "other"},
  {"course": "mmt", "type": "other"},
  {"course": "mmus", "type": "other"},
  {"course": "mn", "type": "other"},
  {"course": "mot", "type": "other"},
  {"course": "mot neurology", "type": "other"},
  {"course": "mot occupational therapy", "type": "other"},
  {"course": "mot orthopaedics", "type": "other"},
  {"course": "mot paediatrics", "type": "other"},
  {"course": "mot psychiatry", "type": "other"},
  {"course": "mpa", "type": "other"},
  {"course": "mpa", "type": "other"},
  {"course": "mpa mridan", "type": "other"},
  {"course": "mpa veena", "type": "other"},
  {"course": "mpa violin", "type": "other"},
  {"course": "mpa vocal", "type": "other"},
  {"course": "mpe", "type": "other"},
  {"course": "mped", "type": "other"},
  {"course": "mpharm", "type": "other"},
  {"course": "mpharm industrial pharmacy", "type": "other"},
  {"course": "mpharm pharmaceutical analysis", "type": "other"},
  {"course": "mpharm pharmaceutical biotechnology", "type": "other"},
  {"course": "mpharm pharmaceutical chemistry", "type": "other"},
  {"course": "mpharm pharmaceutical practice", "type": "other"},
  {"course": "mpharm pharmaceutics", "type": "other"},
  {"course": "mpharm pharmacognosy & phytochemistry", "type": "other"},
  {"course": "mpharm pharmacology", "type": "other"},
  {"course": "mpharm pharmacy practice", "type": "other"},
  {"course": "mpharm pharmagognosy", "type": "other"},
  {"course": "mpharm phytopharmacy & phytomedicine", "type": "other"},
  {"course": "mpharm quality assurance", "type": "other"},
  {"course": "mphil", "type": "other"},
  {"course": "mphil botany", "type": "other"},
  {"course": "mphil clinical epidemiology", "type": "other"},
  {"course": "mphil cultural studies", "type": "other"},
  {"course": "mphil ecological informatics", "type": "other"},
  {"course": "mphil performing arts", "type": "other"},
  {"course": "mphil tamil", "type": "other"},
  {"course": "mphil urdu", "type": "other"},
  {"course": "mpt", "type": "other"},
  {"course": "mpt cardio pulmonary diseases", "type": "other"},
  {"course": "mpt cardio thoracic", "type": "other"},
  {"course": "mpt community physiotherapy", "type": "other"},
  {"course": "mpt hand conditions", "type": "other"},
  {"course": "mpt neurology", "type": "other"},
  {"course": "mpt obstetrics & gynaecology", "type": "other"},
  {"course": "mpt orthopaedics", "type": "other"},
  {"course": "mpt paediatric neurology", "type": "other"},
  {"course": "mpt physiotherapy", "type": "other"},
  {"course": "mpt sports physiotherapy", "type": "other"},
  {"course": "mre", "type": "other"},
  {"course": "mridangam", "type": "other"},
  {"course": "ms", "type": "other"},
  {"course": "ms anatomy", "type": "other"},
  {"course": "ms ent", "type": "other"},
  {"course": "ms general surgery", "type": "other"},
  {"course": "ms obstetrics & gynaecology", "type": "other"},
  {"course": "ms ophthalmology", "type": "other"},
  {"course": "ms orthopaedics", "type": "other"},
  {"course": "ms salya", "type": "other"},
  {"course": "actuarial science", "type": "msc"},
  {"course": "agriculture", "type": "msc"},
  {"course": "analytical chemistry", "type": "msc"},
  {"course": "anatomy", "type": "msc"},
  {"course": "applied", "type": "msc"},
  {"course": "applied chemistry", "type": "msc"},
  {"course": "applied microbiology", "type": "msc"},
  {"course": "applied physics", "type": "msc"},
  {"course": "biochemistry", "type": "msc"},
  {"course": "bioinformatics", "type": "msc"},
  {"course": "biological oceanography & biodiversity", "type": "msc"},
  {"course": "biomaterial & tissue engineering", "type": "msc"},
  {"course": "biostatistics", "type": "msc"},
  {"course": "biotechnology", "type": "msc"},
  {"course": "botany", "type": "msc"},
  {"course": "chemistry", "type": "msc"},
  {"course": "child health nursing", "type": "msc"},
  {"course": "clinical nutrition", "type": "msc"},
  {"course": "community health nursing", "type": "msc"},
  {"course": "computational sciences", "type": "msc"},
  {"course": "computer engineering & network technology", "type": "msc"},
  {"course": "computer science", "type": "msc"},
  {"course": "co-operation, banking & management", "type": "msc"},
  {"course": "counselling psychology", "type": "msc"},
  {"course": "electronics", "type": "msc"},
  {"course": "food science & quality contriol", "type": "msc"},
  {"course": "food science & technology", "type": "msc"},
  {"course": "food technology & quality assurance", "type": "msc"},
  {"course": "forestry", "type": "msc"},
  {"course": "genomics & proteomics", "type": "msc"},
  {"course": "geography", "type": "msc"},
  {"course": "geoinformatics", "type": "msc"},
  {"course": "geology", "type": "msc"},
  {"course": "home science", "type": "msc"},
  {"course": "information science & management", "type": "msc"},
  {"course": "information technology", "type": "msc"},
  {"course": "material science", "type": "msc"},
  {"course": "mathematics", "type": "msc"},
  {"course": "medical & surgical nursing", "type": "msc"},
  {"course": "medical biochemistry", "type": "msc"},
  {"course": "medical physics", "type": "msc"},
  {"course": "medical physiology", "type": "msc"},
  {"course": "medical surgical nursing", "type": "msc"},
  {"course": "mental health nursing", "type": "msc"},
  {"course": "meteorology", "type": "msc"},
  {"course": "microbiology", "type": "msc"},
  {"course": "midwifery & obestrical nursing", "type": "msc"},
  {"course": "mlt", "type": "msc"},
  {"course": "molecular biology & genetic engineering", "type": "msc"},
  {"course": "nursing", "type": "msc"},
  {"course": "obg nursing", "type": "msc"},
  {"course": "operations research & computer applications", "type": "msc"},
  {"course": "paediatric nursing", "type": "msc"},
  {"course": "physical oceanography & ocean modelling", "type": "msc"},
  {"course": "physics", "type": "msc"},
  {"course": "physiology", "type": "msc"},
  {"course": "plant biotechnology", "type": "msc"},
  {"course": "polymer chemistry", "type": "msc"},
  {"course": "psychiatric nursing", "type": "msc"},
  {"course": "psychology", "type": "msc"},
  {"course": "software engineering", "type": "msc"},
  {"course": "toxicology", "type": "msc"},
  {"course": "zoology", "type": "msc"},
  {"course": "msw", "type": "other"},
  {"course": "mta", "type": "other"},
  {"course": "agricultural engineering", "type": "mtech"},
  {"course": "communication engineering", "type": "mtech"},
  {
    "course": "communication engineering and signal processing",
    "type": "mtech"
  },
  {"course": "computer & information science", "type": "mtech"},
  {"course": "computer aided & structural engineer", "type": "mtech"},
  {"course": "computer science", "type": "mtech"},
  {"course": "computer science & engineering", "type": "mtech"},
  {"course": "control systems", "type": "mtech"},
  {"course": "cyber forensic", "type": "mtech"},
  {"course": "digital signal processing", "type": "mtech"},
  {"course": "electro chemical engineering", "type": "mtech"},
  {"course": "electronics", "type": "mtech"},
  {"course": "electronics design technology", "type": "mtech"},
  {
    "course": "electronics with specialization in vlsi & embedded systems",
    "type": "mtech"
  },
  {"course": "embedded systems", "type": "mtech"},
  {"course": "geotechnical engineering", "type": "mtech"},
  {"course": "industrial engineering & management", "type": "mtech"},
  {"course": "machine design", "type": "mtech"},
  {"course": "network engineering", "type": "mtech"},
  {"course": "plastic technology", "type": "mtech"},
  {"course": "power electronics & control", "type": "mtech"},
  {"course": "power systems", "type": "mtech"},
  {"course": "rf and microwave engineering", "type": "mtech"},
  {"course": "signal processing", "type": "mtech"},
  {"course": "structural engineering", "type": "mtech"},
  {"course": "vlsi and microsystems", "type": "mtech"},
  {"course": "mth", "type": "other"},
  {"course": "mvsc", "type": "other"},
  {"course": "nma", "type": "other"},
  {"course": "od", "type": "other"},
  {"course": "pet", "type": "other"},
  {"course": "pg", "type": "other"},
  {"course": "pg diploma adapted physical education", "type": "diploma"},
  {"course": "pg diploma aquarium science & technology", "type": "diploma"},
  {
    "course": "pg diploma computer assisted language teaching",
    "type": "diploma"
  },
  {"course": "pg diploma cyberlaw", "type": "diploma"},
  {"course": "pg diploma e-governance", "type": "diploma"},
  {"course": "pg diploma health & fitness management", "type": "diploma"},
  {"course": "pg diploma hindi translation", "type": "diploma"},
  {"course": "pg diploma industrial aquaculture", "type": "diploma"},
  {"course": "pg dravyaguna vijnana", "type": "other"},
  {"course": "pg panchakarma", "type": "other"},
  {"course": "pg swasthavritha", "type": "other"},
  {"course": "pgdahs", "type": "other"},
  {"course": "pgdcfa", "type": "other"},
  {"course": "pgdcpa", "type": "other"},
  {"course": "pgdit", "type": "other"},
  {"course": "pgdlan", "type": "other"},
  {"course": "pgdm", "type": "other"},
  {"course": "pharmd", "type": "other"},
  {"course": "phb", "type": "other"},
  {"course": "chemistry", "type": "phd"},
  {"course": "commerce", "type": "phd"},
  {"course": "comparative literature", "type": "phd"},
  {"course": "cultural studies", "type": "phd"},
  {"course": "management studies", "type": "phd"},
  {"course": "performing arts", "type": "phd"},
  {"course": "physiology", "type": "phd"},
  {"course": "psycho oncology", "type": "phd"},
  {"course": "social work", "type": "phd"},
  {"course": "sociology", "type": "phd"},
  {"course": "urdu", "type": "phd"},
  {"course": "post afzal ul-ulama", "type": "other"},
  {"course": "post basic bsc nursing", "type": "other"},
  {"course": "post basic nursing", "type": "other"},
  {"course": "sap fico", "type": "other"},
  {"course": "sb", "type": "other"},
  {"course": "scd", "type": "other"},
  {"course": "sjd", "type": "other"},
  {"course": "sscd", "type": "other"},
  {"course": "stb", "type": "other"},
  {"course": "std", "type": "other"},
  {"course": "stm", "type": "other"},
  {"course": "textex", "type": "other"},
  {"course": "tgt", "type": "other"},
  {"course": "thb", "type": "other"},
  {"course": "thd", "type": "other"},
  {"course": "thm", "type": "other"},
  {"course": "ttc", "type": "other"},
  {"course": "veena", "type": "other"},
  {"course": "violin", "type": "other"},
  {"course": "vocal", "type": "other"}
];

const List<Map<String, dynamic>> interests = [
  {
    "name": "Entrepreneurship",
    "icon": "assets/images/office.png",
    "selected": false
  },
  {"name": "Fitness", "icon": "assets/images/fitness.png", "selected": false},
  {
    "name": "Programming Languages",
    "icon": "assets/images/devops.png",
    "selected": false
  },
  {"name": "AI", "icon": "assets/images/AiMl.png", "selected": false},
  {"name": "Bio Hacking", "icon": "assets/images/dna.png", "selected": false},
  {
    "name": "Social Science",
    "icon": "assets/images/social.png",
    "selected": false
  },
  {"name": "Gaming", "icon": "assets/images/gaming.png", "selected": false},
  {
    "name": "Product Management",
    "icon": "assets/images/pm.png",
    "selected": false
  },
  {"name": "Art", "icon": "assets/images/art.png", "selected": false},
  {
    "name": "Machine Learning",
    "icon": "assets/images/devops.png",
    "selected": false
  },
  {"name": "Robotics", "icon": "assets/images/robot.png", "selected": false},
  {
    "name": "Data Science",
    "icon": "assets/images/pager.png",
    "selected": false
  },
  {
    "name": "Life Sciences",
    "icon": "assets/images/social.png",
    "selected": false
  },
  {
    "name": "Volunteering",
    "icon": "assets/images/volunteering.png",
    "selected": false
  },
  {"name": "AR/VR", "icon": "assets/images/ArVr.png", "selected": false},
  {
    "name": "Web Development",
    "icon": "assets/images/web.png",
    "selected": false
  },
  {
    "name": "Product Design",
    "icon": "assets/images/pen.png",
    "selected": false
  },
  {"name": "Sports", "icon": "assets/images/sports.png", "selected": false},
  {"name": "Devops", "icon": "assets/images/devops.png", "selected": false},
  {
    "name": "App Development",
    "icon": "assets/images/app.png",
    "selected": false
  },
  {"name": "Music", "icon": "assets/images/music.png", "selected": false},
];

// programming languages
const List<Map<String, dynamic>> languages = [
  {"title": "Assembly", "icon": "assets/images/assembly.png"},
  {"title": "Bash", "icon": "assets/images/bash.png"},
  {"title": "C#", "icon": "assets/images/c.png"},
  {"title": "C++", "icon": "assets/images/cpp.png"},
  {"title": "Elixir", "icon": "assets/images/elixir.png"},
  {"title": "Flutter", "icon": "assets/images/flutter.png"},
  {"title": "Go", "icon": "assets/images/go.png"},
  {"title": "Haskel", "icon": "assets/images/haskel.png"},
  {"title": "Javascript", "icon": "assets/images/js.png"},
  {"title": "Java", "icon": "assets/images/java.png"},
  {"title": "Julia", "icon": "assets/images/julia.png"},
  {"title": "Kotlin", "icon": "assets/images/kotlin.png"},
  {"title": "Lua", "icon": "assets/images/lua.png"},
  {"title": "OCaml", "icon": "assets/images/ocaml.png"},
  {"title": "PHP", "icon": "assets/images/php.png"},
  {"title": "Python", "icon": "assets/images/python.png"},
  {"title": "R", "icon": "assets/images/r.png"},
  {"title": "Ruby", "icon": "assets/images/ruby.png"},
  {"title": "Rust", "icon": "assets/images/rust.png"},
  {"title": "Swift", "icon": "assets/images/swift.png"},
  {"title": "Zig", "icon": "assets/images/zig.png"},
];

// pupose
const List<String> purpose = [
  'Self Learning',
  'Build a project',
  'Working Proffessional',
  'Researcher',
  "Participant of an event"
];

var thingsToExplore = [
  {
    "iconUrl": "assets/icons/hacker_space.svg",
    "title": "Hackerspace",
    "subtitle": "A place to elevate your \nlearning experience",
    "color": "0xFF3CD377",
  },
  {
    "iconUrl": "assets/icons/maker_station.svg",
    "title": "Maker Station",
    "subtitle": "Your hub for DIY and\n hardware crafts",
    "color": "0xFFFD9800",
  },
  {
    "iconUrl": "assets/icons/vr_zone.svg",
    "title": "VR Zone",
    "subtitle": "Dive into immersive virtual \nworlds",
    "color": "0xFF5F5CE5",
  },
  {
    "iconUrl": "assets/icons/gpu_station.svg",
    "title": "GPU Stations",
    "subtitle": "Perfect for advanced \ncomputing and coding",
    "color": "0xFFB720FF",
  },
  {
    "iconUrl": "assets/icons/ai.svg",
    "title": "AI Experience",
    "subtitle": "Navigate machine learning's \nvast horizons",
    "color": "0xFFFF0059",
  },
  {
    "iconUrl": "assets/icons/3d_printing.svg",
    "title": "3D Printing",
    "subtitle": "Turn designs into tangible \ncreations",
    "color": "0xFF189CF1",
  }
];
